version: "3"
services:
  dnsmasq:
    image: autechgemz/dnsmasq
    container_name: dnsmasq
    network_mode: host
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./dnsmasq.conf:/etc/dnsmasq.conf"
