version: "3.4"
services:
  dnsmasq:
    image: autechgemz/dnsmasq
    container_name: dnsmasq
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD","dig","@localhost","localhost","+norec"]
      interval: 5m
      timeout: 10s
      retries: 3
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./dnsmasq.conf:/etc/dnsmasq.conf"
