version: "3.4"
services:
  dnsmasq:
    build:
      context: .
    image: autechgemz/dnsmasq
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD","dig","@localhost","localhost","+norec"]
      interval: 5m
      timeout: 10s
      retries: 3
